apiVersion: v1
kind: Service
metadata:
  name: goordersb
  labels:
    app: goordersb
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    run: goordersb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goordersb
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: goordersb
        app: goordersb
    spec:
      containers:
      - name: goordersb
        image: cadcontainerregistry.azurecr.io/go_order_sb
        env:
        - name: DATABASE
          value: "k8orders"
        - name: PASSWORD
          value: "p0L8xLDJJ6oMVqRunukpR4IYAMCoAhSrMFO1bbV1UM5cR4yPZ2Mmk0P76zfYQcBAo7XI9mdRJ5qb7kfjOSRSxQ=="
        - name: INSIGHTSKEY
          value: "720740f8-75d7-410a-a038-0ea704127c5f"
        - name: SOURCE
          value: "K8"
        ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: cadcontainerregistry